Gradient Descent

In [6]:
import tensorflow as tf

Initialization of tensors

In [11]:
x = tf.constant(4.4)
x1 = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor(4.4, shape=(), dtype=float32)


In [14]:
x3 = tf.ones((3,3))
print(x3)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x4 = tf.ones((3,3))
print(x4)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [17]:
x4 = tf.eye((3))
print(x4)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
norm = tf.random.normal((3,3), 3.4, 3.4,)
print(norm)

tf.Tensor(
[[7.649608  4.877096  6.812676 ]
 [3.2273185 2.1782255 3.0279992]
 [2.2086565 5.702361  3.3033059]], shape=(3, 3), dtype=float32)


In [22]:
uniform = tf.random.uniform((3,3), minval=0, maxval=1)
print(uniform)

tf.Tensor(
[[0.4287336  0.03152454 0.96483064]
 [0.7469518  0.9364188  0.9248824 ]
 [0.29791856 0.6031246  0.500659  ]], shape=(3, 3), dtype=float32)


In [26]:
tf.range(9)
y= tf.range(start=1, limit=20, delta=4)

In [28]:
y =  tf.cast(y, dtype=tf.float64)

Mathematical Operation

In [29]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])


z = x + y

In [30]:
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [31]:
tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>